### ISSUE TITLE
Micronaut 1.0.0.M4 Compatibility

### ISSUE THREAD

**Issue by fmayoral** [looorent/keycloak-micronaut-adapter#1]
Hello!
I'm trying to use this with Micronaut 1.0.0.M4 and it seems to fail when loading some class definition.
It works by just changing the version to the latest in this library and publishing it locally. All tests pass and it seems to work for my service. I suppose that since Micronaut generates the class definitions at compile time, and that the contract got broken in between milestones then this adapter won't work with different milestones, even though nothing is wrong with it.

Are there any plans to keep this up with the latest milestones or even final release?
Also, are you accepting contributions to this project? So far I'm interested in having this running with latest Micronaut and not looking into feature development.

Thanks!

**Comment by graemerocher** [comment]
Note that once we release the RC on the 30th of September we won't be making any changes to the generated byte code format again. So only one more release will be needed

**Comment by looorent** [comment]
@fmayoral Hello! Sorry for the delay and thank you for using this project. I agree with you, the generated class definitions do not seem to work with Micronaut 1.0.0.M4.

If the RC solves this problem, it's just a matter of time. In the meanwhile, I published a version `1.3.0` that supports Micronaut 1.0.0.M4. Feel free to use it.

I definitively will keep this library up-to-date! And all contributions are welcome, of course. :)


@graemerocher Good to know! Do you know whether generating class definitions directly in micronaut libraries (like this one) is bad practice or not? Is there an other way to develop libraries for Micronaut without bundling their class definitions with them?

**Comment by graemerocher** [comment]
@looorent Just to clear the RC won't fix the problem. The RC will finalise the binary class format that Micronaut uses so that we will ensure going forward that binary compatibility is not broken with new releases of Micronaut. So you will be able to do a release when the RC is out and that release will work with future versions of Micronaut

It is not considered bad practise and currently there is no way to build Micronaut libraries without bundling the class definitions

**Comment by looorent** [comment]
@graemerocher That's clear. Thank you!

**Comment by fmayoral** [comment]
Sweet! thank you very much @looorent ! and also tank you @graemerocher for your comments
