### ISSUE TITLE
I had a problem with you SecurityFilter.class

### ISSUE THREAD

**Issue by fricred** [looorent/keycloak-micronaut-adapter#2]
When i implement your adapter i cant lauch custom exeptions 
because you catch all and response for me 

```
 private MutableHttpResponse<?> unexpectedError(Throwable error) {
        UUID errorId = randomUUID();
        LOG.error("Internal error when retrieving a parking site access: {}", errorId, error);
        String message = "An internal error occurred, please contact us by providing this ID: " + errorId;
        return status(INTERNAL_SERVER_ERROR).body(new JsonError(message));
    }
```
is an expected error

**Comment by djeverson** [comment]
+1- trying to return a custom response for constraint violations and it is not working.  I expect the user to get a 400 with a list of the errors.  However, this replaces that with a 500 and cryptic message.  Can this check be disabled?  I tried replacing this class in my app but was unable.

**Comment by looorent** [comment]
You are both right. Thank you for this feedback.
A new version 1.5.0 is now available. (tested on Micronaut 1.0.2)
