### ISSUE TITLE
Micronaut 2.0.0 compatibility

### ISSUE THREAD

**Issue by oscarfh** [looorent/keycloak-micronaut-adapter#4]
Hi @looorent ,
Is this project still under development? There is a problem with the newest micronaut version.
Let me know if this is still alive. If it is, I will create a PR to adapt it to micronaut 2.0.0

thanks!

**Comment by looorent** [comment]
Hi @oscarfh,

This project is still alive. You can create a PR, I would be happy to push a new version of this lib.

**Comment by oscarfh** [comment]
Wow, that was fast!
Yes, I will do it today or over the weekend!

**Comment by oscarfh** [comment]
PR is created: https://github.com/looorent/keycloak-micronaut-adapter/pull/5

**Comment by looorent** [comment]
Thanks @oscarfh .
This has been released in version 2.0.0. It should be available in the next hour on Maven Central.
